{{ config(
    materialized='view',
    schema='bronze'
) }}

{#
    Bronze layer: Map Vietnamese column names to English
    Source: raw.raw_orders (547 rows, 70 columns)
#}

select
    "Mã đơn hàng" as order_id,
    "Mã Kiện Hàng" as package_id,
    "Ngày đặt hàng" as order_date,
    "Trạng Thái Đơn Hàng" as order_status,
    "Sản Phẩm Bán Chạy" as is_bestseller,
    "Nhận xét từ Người mua" as buyer_review,
    "Mã vận đơn" as tracking_number,
    "Đơn Vị Vận Chuyển" as shipping_carrier,
    "Phương thức giao hàng" as shipping_method,
    "Loại đơn hàng" as order_type,
    "Ngày giao hàng dự kiến" as expected_delivery_date,
    "Ngày gửi hàng" as ship_date,
    "Thời gian giao hàng" as actual_delivery_date,
    "Trạng thái Trả hàng/Hoàn tiền" as return_status,
    "SKU sản phẩm" as product_sku,
    "Tên sản phẩm" as product_name,
    "Cân nặng sản phẩm" as product_weight,
    "Tổng cân nặng" as total_weight,
    "SKU phân loại hàng" as variant_sku,
    "Tên phân loại hàng" as variant_name,
    "Giá gốc" as original_price,
    "Người bán trợ giá" as seller_discount,
    "Được Shopee trợ giá" as shopee_discount,
    "Tổng số tiền được người bán trợ giá" as total_seller_discount,
    "Giá ưu đãi" as discount_price,
    "Số lượng" as quantity,
    "Số lượng sản phẩm được hoàn trả" as returned_quantity,
    "Tổng giá bán (sản phẩm)" as total_product_price,
    "Tổng giá trị đơn hàng (VND)" as order_total_vnd,
    "Mã giảm giá của Shop" as shop_voucher,
    "Hoàn Xu" as coins_cashback,
    "Mã giảm giá của Shopee" as shopee_voucher,
    "Chỉ tiêu Combo Khuyến Mãi" as combo_promo_target,
    "Giảm giá từ combo Shopee" as shopee_combo_discount,
    "Giảm giá từ Combo của Shop" as shop_combo_discount,
    "Shopee Xu được hoàn" as shopee_coins_returned,
    "Số tiền được giảm khi thanh toán bằng thẻ Ghi nợ" as debit_card_discount,
    "Trade-in Discount" as tradein_discount,
    "Trade-in Bonus" as tradein_bonus,
    "Phí vận chuyển (dự kiến)" as shipping_fee_estimated,
    "Trade-in Bonus by Seller" as tradein_bonus_seller,
    "Phí vận chuyển mà người mua trả" as shipping_fee_paid,
    "Phí vận chuyển tài trợ bởi Shopee (dự kiến)" as shipping_subsidy,
    "Phí trả hàng" as return_fee,
    "Tổng số tiền người mua thanh toán" as total_paid,
    "Thời gian hoàn thành đơn hàng" as order_completed_date,
    "Thời gian đơn hàng được thanh toán" as payment_date,
    "Phương thức thanh toán" as payment_method,
    "Phí cố định" as fixed_fee,
    "Phí Dịch Vụ" as service_fee,
    "Phí thanh toán" as payment_fee,
    "Tiền ký quỹ" as deposit,
    "Người Mua" as buyer_username,
    "Tên Người nhận" as recipient_name,
    "Số điện thoại" as phone_number,
    "Tỉnh/Thành phố" as province,
    "TP / Quận / Huyện" as district,
    "Quận" as ward,
    "Địa chỉ nhận hàng" as shipping_address,
    "Quốc gia" as country,
    "Ghi chú" as note,
    "source_file" as source_file,
    'shopee_seller_center' as _source_system,
    current_timestamp as _bronze_loaded_at

from {{ source('raw', 'raw_orders') }}